[workspace]
members = ["server", "client"]

[workspace.package]
authors = ["Victor Kostyuk <victor@kosty.uk>"]
description = "Aggregator of order books from different cryptocurrency exchanges"
repository = "https://github.com/torcoste/orderbook-aggregator"
